[package]
name = "gomoku"
version = "1.0.0"
authors = ["Frontier789 <fr0nt13r789@gmail.com>"]
edition = "2018"

[dependencies]
glui = { git = "https://github.com/Frontier789/glui" }
glui_proc = { git = "https://github.com/Frontier789/glui_proc" }
rand = "*"
serde_json = "*"
chrono = "*"
