[package]
name = "gomoku"
version = "1.0.0"
authors = ["Frontier789 <fr0nt13r789@gmail.com>"]
edition = "2018"

[dependencies]
glui = { path = "../glui" }
glui_proc = { path = "../glui_proc" }
rand = "*"
serde_json = "*"
chrono = "*"
